FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    build-essential libpq-dev git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy requirements & install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy semua file (agar script di bin/ bisa terbaca)
COPY . .

# Buat folder output jika belum ada
RUN mkdir -p data output

EXPOSE 8001

# Jalankan FastAPI (api.py)
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8001"]